using Asp.Versioning;
using Maliev.Aspire.ServiceDefaults.Authorization;
using Maliev.PdfService.Api.Authorization;
using Maliev.PdfService.Api.Models.Data;
using Maliev.PdfService.Api.Services;
using Maliev.PdfService.Domain.Entities;
using Microsoft.AspNetCore.Mvc;

namespace Maliev.PdfService.Api.Controllers;

/// <summary>
/// Controller for rendering customer-facing blog practical note PDFs.
/// </summary>
[ApiVersion("1")]
[Route("pdf/v{version:apiVersion}/blog-practical-notes")]
[ApiController]
public sealed class BlogPracticalNotesController(IPdfGenerator pdfGenerator) : ControllerBase
{
    /// <summary>
    /// Renders a blog practical note PDF and returns the generated bytes directly.
    /// </summary>
    /// <param name="request">The practical note data.</param>
    /// <returns>The rendered PDF file.</returns>
    [HttpPost("render")]
    [RequirePermission(PdfPermissions.GenerationCreate)]
    [Produces("application/pdf")]
    [ProducesResponseType(typeof(FileContentResult), StatusCodes.Status200OK)]
    public async Task<IActionResult> Render([FromBody] BlogPracticalNoteData request)
    {
        var pdfBytes = await pdfGenerator.GeneratePdfAsync(DocumentType.BlogPracticalNote, request);
        return File(pdfBytes, "application/pdf", $"{SanitizeFileName(request.Slug)}-maliev-practical-note.pdf");
    }

    private static string SanitizeFileName(string value)
    {
        var invalidCharacters = Path.GetInvalidFileNameChars();
        var safe = new string(value.Select(character => invalidCharacters.Contains(character) ? '-' : character).ToArray());
        return string.IsNullOrWhiteSpace(safe) ? "maliev-practical-note" : safe;
    }
}
